/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/entities/$entityId',
  path: '/entities/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/entities': typeof EntitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/graph': typeof GraphRoute
  '/timeline': typeof TimelineRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/graph'
    | '/timeline'
    | '/entities/$entityId'
    | '/entities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/graph'
    | '/timeline'
    | '/entities/$entityId'
    | '/entities'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/graph'
    | '/timeline'
    | '/entities/$entityId'
    | '/entities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  GraphRoute: typeof GraphRoute
  TimelineRoute: typeof TimelineRoute
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  GraphRoute: GraphRoute,
  TimelineRoute: TimelineRoute,
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
